### PR TITLE
TB versions after 2.1 should work with TF 2.1

### PR DESCRIPTION
**Pull request by psybuzz**
TB 2.1.0 works great with TF 2.1.0.  However, tip-of-tree TB doesn't work with TF 2.1.0, since ToT TB depends on TF's DebugDataReader, which was introduced after TF 2.1.0.  Running this combination produces:

```
AttributeError: module 'tensorflow.python.debug.lib.debug_events_reader' has no attribute 'DebugDataReader'
```

@caisq, do we plan to support, say, TB 2.2 or ToT TB working with TF 2.1?
If not, we can close this.

### CODE REVIEW

File: tensorboard/plugins/debugger_v2/debug_data_multiplexer.py [hunk 1]
```diff
@@ -115,6 +115,10 @@ def Runs(self):
                 self._reader.update()
                 # TODO(cais): Start off a reading thread here, instead of being
                 # called only once here.
+            except AttributeError as error:
```
Comment (caisq) [inline tensorboard/plugins/debugger_v2/debug_data_multiplexer.py]: Instead of this, what do you think about checking

```py
if tensorflow.__version__ <= "2.1.0":
  return {}
```

Comment (psybuzz) [reply tensorboard/plugins/debugger_v2/debug_data_multiplexer.py]: I'd still like to investigate why the tb-nightly packager failed, and why it was using tensorflow 2.1.0.dev20200102 when it ran on Jan 9.  Then, it would be nice if we gracefully failed when running ToT TB with TF 2.1.0.dev20200102.

So it would make sense to do a check like:
`if parse_version(tf_version) < parse_version("2.1.0.dev20200103"):`

I don't fully understand why, but tf-nightlies are still marked with major/minor "2.1.0", so this check would fail.  That is, "2.1.0" was released before "2.1.0.dev20200103", but parse_version thinks that the former is greater than the latter.

Would it suffice to keep the AttributeError check for now, and have a more descriptive comment that it should be safe to remove when TF 2.2 is released and stable?

Comment (caisq) [reply tensorboard/plugins/debugger_v2/debug_data_multiplexer.py]: The change that started around 20200103 does look strange and needs investigation for full understanding. I'll approve the `AttributeError` approach now to unblock builds.

File: tensorboard/plugins/debugger_v2/debug_data_multiplexer.py [hunk 2]
```diff
@@ -115,6 +115,11 @@ def Runs(self):
...
+                # Gracefully fail for users without the required API changes to
+                # debug_events_reader introduced in TF 2.1.0.dev20200103.
```
Comment (caisq) [inline tensorboard/plugins/debugger_v2/debug_data_multiplexer.py]: nit: debug_events_reader.DebugDataReader to be precise.

Comment (psybuzz) [reply tensorboard/plugins/debugger_v2/debug_data_multiplexer.py]: Done.

File: tensorboard/plugins/debugger_v2/debug_data_multiplexer.py (hunk 1 above)
Comment (wchargin) [reply tensorboard/plugins/debugger_v2/debug_data_multiplexer.py]: > I don't fully understand why, but tf-nightlies are still marked with
> major/minor "2.1.0", so this check would fail. That is, "2.1.0" was
> released before "2.1.0.dev20200103", but parse_version thinks that the
> former is greater than the latter.

TensorFlow 2.1.0 was released on 2020-01-08, after the 2020-01-03
nightly.

The behavior of `parse_version` is correct: `.devWHATEVER` is a
[pre-release specifier, as listed in PEP 440][pep-440].

TensorFlow’s 2.1.0 version bump was just merged into master a few hours
ago, so we should expect tomorrow’s nightly to be `2.2.0.dev20200111`:
<https://github.com/tensorflow/tensorflow/commit/f6404f4f24e756196fd710c27243e10f625ac2e8>

[pep-440]: https://www.python.org/dev/peps/pep-0440/#pre-releases
