### ISSUE TITLE
Serving runs hits AttributeError in py3 from bad dict key sort

### ISSUE THREAD

**Issue by robieta** [tensorflow/tensorboard#1003]
I am running Ubuntu 16.04.3 using the builtin python 3.5.2 running resnet (https://github.com/tensorflow/models/tree/master/official/resnet) on imagenet. When I try to run tensorboard (using python3) I get the following error:

> Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/tensorboard/backend/application.py", line 266, in __call__
    return self.data_applications[clean_path](environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/wrappers.py", line 308, in application
    resp = f(*args[:-2] + (request,))
  File "/usr/local/lib/python3.5/dist-packages/tensorboard/plugins/core/core_plugin.py", line 164, in _serve_runs
    run_names.sort(key=first_event_time_values.get)
AttributeError: 'dict_keys' object has no attribute 'sort'

However, tensorboard runs fine with python2. The issue appears to be that in Py3 the .keys() method no longer returns a list, and thus the .sort() method is not defined for the new py3 dict keys object.

**Comment by nfelt** [comment]
Thanks for the report!  I assume this is using tf-nightly or building from head?  It looks like this was just introduced by #985, I'll work on a fix.

**Comment by robieta** [comment]
Correct, this is tf-nightly. Apologies for not including that in the initial description.
