### ISSUE TITLE
AttributeError: module 'tensorflow._api.v2.errors' has no attribute 'raise_exception_on_not_ok_status'

### ISSUE THREAD

**Issue by sanidhyamangal** [tensorflow/tensorboard#2619]
Tensorboard - 13.0.0
TensorFlow - 2.0.0b1

Hi there I am getting following output after running following command
```cmd
tensorboard --logdir tf_modelv2
```

Output:

```cmd
Exception in thread Reloader:
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "c:\programdata\anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "c:\programdata\anaconda3\lib\site-packages\tensorboard\backend\application.py", line 391, in _reload
    multiplexer.Reload()
  File "c:\programdata\anaconda3\lib\site-packages\tensorboard\backend\event_processing\plugin_event_multiplexer.py", line 240, in Reload
    Worker()
  File "c:\programdata\anaconda3\lib\site-packages\tensorboard\backend\event_processing\plugin_event_multiplexer.py", line 218, in Worker
    accumulator.Reload()
  File "c:\programdata\anaconda3\lib\site-packages\tensorboard\backend\event_processing\plugin_event_accumulator.py", line 177, in Reload
    for event in self._generator.Load():
  File "c:\programdata\anaconda3\lib\site-packages\tensorboard\backend\event_processing\directory_watcher.py", line 89, in Load
    for event in self._LoadInternal():
  File "c:\programdata\anaconda3\lib\site-packages\tensorboard\backend\event_processing\directory_watcher.py", line 109, in _LoadInternal
    self._InitializeLoader()
  File "c:\programdata\anaconda3\lib\site-packages\tensorboard\backend\event_processing\directory_watcher.py", line 168, in _InitializeLoader
    self._SetPath(path)
  File "c:\programdata\anaconda3\lib\site-packages\tensorboard\backend\event_processing\directory_watcher.py", line 192, in _SetPath
    self._loader = self._loader_factory(path)
  File "c:\programdata\anaconda3\lib\site-packages\tensorboard\backend\event_processing\event_file_loader.py", line 40, in __init__
    with tf.errors.raise_exception_on_not_ok_status() as status:
AttributeError: module 'tensorflow._api.v2.errors' has no attribute 'raise_exception_on_not_ok_status'

TensorBoard 1.13.0 at http://Sanidhya:6006 (Press CTRL+C to quit)
```

**Comment by wchargin** [comment]
Hi @sanidhyamangal! TensorFlow 2.x requires a compatible version of
TensorBoard, and will not work with 1.13.x. Please **uninstall** any
copies of `tensorboard` or `tb-nightly` that you may have installed, and
then run `pip install tb-nightly` to grab the latest version.
