### ISSUE TITLE
Enlarge button makes the graph in custom_scalar plugin becomes very narrow

### ISSUE THREAD

**Issue by lanpa** [tensorflow/tensorboard#4771]
## Environment information (required)

<details>

``````

--- check: full_pip_freeze
INFO: pip freeze --all:
absl-py==0.12.0
astor==0.8.1
cached-property==1.5.2
certifi==2020.12.5
gast==0.2.2
google-pasta==0.2.0
grpcio==1.36.1
h5py==3.2.1
importlib-metadata==3.7.3
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.2
Markdown==3.3.4
numpy==1.20.1
opt-einsum==3.3.0
pip==21.0.1
protobuf==3.15.6
setuptools==52.0.0.post20210125
six==1.15.0
tensorboard==1.15.0
tensorflow==1.15.0
tensorflow-estimator==1.15.1
termcolor==1.1.0
typing-extensions==3.7.4.3
Werkzeug==1.0.1
wheel==0.36.2
wrapt==1.12.1
zipp==3.4.1

``````

</details>

  - Chrome Version 89.0.4389.82 (Official Build)

![image](https://user-images.githubusercontent.com/2005323/111076267-9c273a00-8526-11eb-9907-dcb13116acc0.png)

## Issue description

To reproduce:
- run https://github.com/tensorflow/tensorboard/blob/50e0555f98c14a3aabcef7225ff9c72a0eea4173/tensorboard/plugins/custom_scalar/custom_scalar_demo.py
- open TensorBoard
- Click on the enlarge button, the graph will become very narrow.

Originally reported by @yllgl
https://github.com/lanpa/tensorboardX/issues/613

**Comment by psybuzz** [comment]
Thanks for the report.  I can reproduce this with tensorboard==2.2.2 (the version bundled with tensorboardX 2.1).  However, this issue looks fixed when I try it with newer versions of tensorboard (both 2.3.0 and 2.4.1).
![image](https://user-images.githubusercontent.com/2322480/111219213-fe1e8880-8594-11eb-9c89-e7e2786b6801.png)

Could you please upgrade the TensorBoard version and let us know if it is still broken?

**Comment by lanpa** [comment]
@psybuzz Yes, After I changed to 2.4.1 the error is gone. I used the older version (1.15) because the demo code `custom_scalar_demo.py` does not work with TF 2.4.1.

As an FYI, the error message is:
```
  File "custom_scalar_demo.py", line 62, in run
    with tf.compat.v1.Session() as sess, tf.summary.FileWriter(
AttributeError: module 'tensorboard.summary._tf.summary' has no attribute 'FileWriter'

------------------------------------------
tensorboard            2.4.1
tensorboard-plugin-wit 1.8.0
tensorflow             2.4.1
tensorflow-estimator   2.4.0

```
Thanks for looking into this!

**Comment by psybuzz** [comment]
Glad to hear!  Yeah, many of the demos in the repo are unfortunately outdated.  If you or folks you know are interested in the demos, please follow https://github.com/tensorflow/tensorboard/issues/3058 for updates :)
